# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [48]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.89237073, 0.84059698, 0.63123084, 0.3864126 , 0.93375722,
        0.22581689, 0.79228576, 0.69106202, 0.80915714, 0.55000559],
       [0.2428513 , 0.04471785, 0.2042642 , 0.84622941, 0.04312327,
        0.18877708, 0.702102  , 0.77086989, 0.10957432, 0.25306969],
       [0.44413954, 0.79338275, 0.16591895, 0.93187675, 0.40228388,
        0.24945838, 0.9991146 , 0.37026004, 0.42290855, 0.59610859],
       [0.65747059, 0.32168644, 0.05421714, 0.26464509, 0.17171412,
        0.7013119 , 0.37590487, 0.35841109, 0.37622977, 0.27611018],
       [0.5556432 , 0.39332521, 0.58587925, 0.17667599, 0.967363  ,
        0.1043723 , 0.17781682, 0.76783943, 0.26634631, 0.32361344],
       [0.90847555, 0.57414216, 0.95327827, 0.83305182, 0.96077279,
        0.53883943, 0.33963702, 0.20826157, 0.56604521, 0.78325076],
       [0.73544602, 0.6220439 , 0.68602123, 0.65144242, 0.84170771,
        0.13467759, 0.95442664, 0.69283918, 0.98612944, 0.89209944],
       [0.31917846, 0.25126301, 0.7411418

In [49]:
#3.3: return only the odd rows of A
A[::2]

array([[0.89237073, 0.84059698, 0.63123084, 0.3864126 , 0.93375722,
        0.22581689, 0.79228576, 0.69106202, 0.80915714, 0.55000559],
       [0.44413954, 0.79338275, 0.16591895, 0.93187675, 0.40228388,
        0.24945838, 0.9991146 , 0.37026004, 0.42290855, 0.59610859],
       [0.5556432 , 0.39332521, 0.58587925, 0.17667599, 0.967363  ,
        0.1043723 , 0.17781682, 0.76783943, 0.26634631, 0.32361344],
       [0.73544602, 0.6220439 , 0.68602123, 0.65144242, 0.84170771,
        0.13467759, 0.95442664, 0.69283918, 0.98612944, 0.89209944],
       [0.21113692, 0.13068867, 0.03992636, 0.88920997, 0.45817839,
        0.90027768, 0.40777916, 0.07675142, 0.19274344, 0.00277558]])

In [50]:
#3.4: perform a matrix multiplication of A with it's transposed
B = np.dot(A,A.T)
B

array([[5.03611657, 2.10996728, 3.6775612 , 2.31410877, 3.25642543,
        4.53759016, 5.20387202, 3.42776102, 1.83180282, 2.82753717],
       [2.10996728, 2.01953933, 2.21435048, 1.2001864 , 1.31096017,
        1.9483681 , 2.49755254, 2.21090041, 1.37475015, 1.41797469],
       [3.6775612 , 2.21435048, 3.61622088, 1.87884715, 2.00338889,
        3.43712948, 4.0721924 , 2.76965879, 1.96062211, 1.90225956],
       [2.31410877, 1.2001864 , 1.87884715, 1.61759903, 1.34127975,
        2.22855058, 2.35664031, 1.69155571, 1.3824749 , 1.7680738 ],
       [3.25642543, 1.31096017, 2.00338889, 1.34127975, 2.58145997,
        3.04649417, 3.25167414, 2.49291774, 1.07008037, 1.93646311],
       [4.53759016, 1.9483681 , 3.43712948, 2.22855058, 3.04649417,
        5.06372925, 4.82857205, 3.63291482, 2.23673271, 2.61713918],
       [5.20387202, 2.49755254, 4.0721924 , 2.35664031, 3.25167414,
        4.82857205, 5.70868077, 3.85065377, 1.9850506 , 2.84712039],
       [3.42776102, 2.21090041, 2.7696587

In [51]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)


array([[-0.51593408,  1.25632013,  0.00893107, -0.83287845,  0.20109466,
         1.35013184, -0.14703786, -1.93559211, -0.33980986,  1.40602595],
       [ 1.70724152, -1.05244461,  1.17841519,  0.25203079, -0.54111062,
        -0.38462504, -1.81205182,  1.26168523, -0.49456311, -0.33079589],
       [ 3.01030564,  0.67341946, -1.63051991,  0.63304034, -1.67181578,
         0.44793261, -1.47860512,  1.44553951, -0.43667904, -1.57998743],
       [-0.57176404,  0.3990093 ,  0.73613556, -1.88174573, -0.23150376,
         0.63843357, -0.14574812, -0.48922097,  0.42113924,  1.27044664],
       [-1.38641177, -0.45711055,  0.29351366, -0.69792545,  1.65222416,
        -0.16681737,  1.04165794, -0.88317039,  0.84642518,  0.30019067],
       [ 0.41121057, -0.60685323, -0.52854534,  2.16044812, -0.13849237,
        -0.52810479, -0.31440574,  1.15443339,  0.26132449, -1.26356513],
       [ 1.02095428,  0.91081551, -0.76008858,  0.84248727, -0.33109215,
        -0.28727625,  0.21136065, -0.28553566

In [6]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )

In [60]:
mask = (0.5 < A)
np.where(mask)
A[np.where(mask)]/2

array([0.44618537, 0.42029849, 0.31561542, 0.46687861, 0.39614288,
       0.34553101, 0.40457857, 0.27500279, 0.42311471, 0.351051  ,
       0.38543495, 0.39669137, 0.46593837, 0.4995573 , 0.2980543 ,
       0.3287353 , 0.35065595, 0.2778216 , 0.29293962, 0.4836815 ,
       0.38391971, 0.45423778, 0.28707108, 0.47663914, 0.41652591,
       0.4803864 , 0.26941971, 0.2830226 , 0.39162538, 0.36772301,
       0.31102195, 0.34301062, 0.32572121, 0.42085386, 0.47721332,
       0.34641959, 0.49306472, 0.44604972, 0.37057093, 0.47726537,
       0.26472779, 0.46320031, 0.28609626, 0.44460498, 0.45013884,
       0.41191182, 0.27361864, 0.41563542, 0.31851916])